name: DigitalOcean App Platform deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: clownfish-app-2
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
